name: Upload Node.js 14 and 16 tool cache
on: push
jobs:
  upload_tool_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          mkdir -p "${{ runner.tool_cache }}"
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Archive tool cache
        run: |
          ls "${{ runner.tool_cache }}"
          cd "${{ runner.tool_cache }}"
          tar -czf tool_cache.tar.gz ${{runner.tool_cache}}/*
      
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{runner.tool_cache}}/tool_cache.tar.gz
        env:
          GITHUB_TOKEN: ${{ github.token }} 
